#!/usr/bin/env bash
# setup.sh — 1Password から .mcp.json と .env を生成する（idempotent）
#
# 生成物:
#   .mcp.json               — mcp-wordpress 用（git 管理外）
#   .env                    — wp-admin ログイン / GA・GSC SA パス / Clarity トークン（git 管理外）
#   service-account-ga4.json — GA4 / Search Console 用 SA キー（git 管理外）
#
# 1Password の配置（実測済み 2026-09-14）:
#   vault `磯貝プライベート共有` (vuhhrti25x7eq7g46mwtq7qome):
#     - `programming-life.net` (v3hyideaoxwzyh57hkpfomzbhm) … wp-admin 通常ログイン
#   vault `RITMO` (gq4pz3xxmoryoteuhvamcktmaq):
#     - `programming-life.net MCP App Password` (z6aqtnrri66rktwhpoaamubjjy) … REST API 用
#     - `Microsoft Clarity APIキー` (xufjwbxd6bbexcjgvw5mfhlysy)              … Data Export API
#     - `programming-life.net GA Service Account` … GA4/GSC 用 JSON キー（`credential` フィールド）
set -euo pipefail

PRIVATE_VAULT="vuhhrti25x7eq7g46mwtq7qome"
RITMO_VAULT="gq4pz3xxmoryoteuhvamcktmaq"
LOGIN_ITEM_ID="v3hyideaoxwzyh57hkpfomzbhm"
APP_PW_ITEM_ID="z6aqtnrri66rktwhpoaamubjjy"
CLARITY_ITEM_ID="xufjwbxd6bbexcjgvw5mfhlysy"
GA_SA_ITEM_NAME="programming-life.net GA Service Account"

MCP_JSON=".mcp.json"
ENV_FILE=".env"
SA_JSON="service-account-ga4.json"

# サービスアカウント鍵の正本は ~/.config/op/service-account-token（.envrc 経由だと
# direnv 専用関数で死ぬため直接読む）
if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] && [ -r "$HOME/.config/op/service-account-token" ]; then
  export OP_SERVICE_ACCOUNT_TOKEN="$(cat "$HOME/.config/op/service-account-token")"
fi

command -v op >/dev/null || { echo "[ERROR] op (1Password CLI) not found." >&2; exit 1; }

echo "[setup] Fetching WordPress credentials from 1Password..."

APP_PW=$(op item get "$APP_PW_ITEM_ID" --vault "$RITMO_VAULT" --fields password --reveal </dev/null 2>/dev/null || true)
[ -n "$APP_PW" ] || { echo "[ERROR] MCP App Password not found (RITMO/$APP_PW_ITEM_ID)." >&2; exit 1; }
# フィールドが '"値\n値"' と二重・引用符付きで保存されている実績があるため正規化する
# （同一行の重複は先頭を採用。WP Application Password はスペースなし24文字）
APP_PW=$(printf '%s' "$APP_PW" | sed 's/^"//; s/"$//' | awk 'NF && !seen[$0]++' | head -1 | tr -d '[:space:]')

WP_USER=$(op item get "$LOGIN_ITEM_ID" --vault "$PRIVATE_VAULT" --fields username </dev/null 2>/dev/null || true)
WP_ADMIN_PW=$(op item get "$LOGIN_ITEM_ID" --vault "$PRIVATE_VAULT" --fields password --reveal </dev/null 2>/dev/null || true)
[ -n "$WP_USER" ] || { echo "[ERROR] wp-admin username not found ($PRIVATE_VAULT/$LOGIN_ITEM_ID)." >&2; exit 1; }

echo "[setup] Writing $MCP_JSON ..."
# 秘密値に引用符等が混入していても壊れないよう jq で組み立てる
jq -n --arg user "$WP_USER" --arg pw "$APP_PW" '{
  mcpServers: {
    "wordpress-programming-life": {
      command: "npx",
      args: ["-y", "mcp-wordpress"],
      env: {
        WORDPRESS_SITE_URL: "https://programming-life.net",
        WORDPRESS_USERNAME: $user,
        WORDPRESS_APP_PASSWORD: $pw,
        WORDPRESS_AUTH_METHOD: "app-password"
      }
    }
  }
}' > "$MCP_JSON"

echo "[setup] Writing $ENV_FILE ..."
{
  echo "# Generated by setup.sh — do not commit"
  echo "WP_ADMIN_URL=https://programming-life.net/login_49954"
  echo "WP_ADMIN_USER=\"$WP_USER\""
  echo "WP_ADMIN_PASSWORD=\"$WP_ADMIN_PW\""
} > "$ENV_FILE"

MISSING=()

echo "[setup] Fetching analytics credentials (vault: RITMO)..."
# --fields 出力は値が引用符を含むとCSVエスケープされるため --format json から取り出す
if op item get "$GA_SA_ITEM_NAME" --vault "$RITMO_VAULT" \
    --reveal --format json </dev/null 2>/dev/null | node -e '
      let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
        const d=JSON.parse(s);
        const f=(d.fields||[]).find(f=>f.label==="credential"||f.id==="credential");
        if(!f||!f.value)process.exit(1);
        JSON.parse(f.value); // SA JSON として妥当か検証
        process.stdout.write(f.value);
      });' > "$SA_JSON" && [ -s "$SA_JSON" ]; then
  echo "GOOGLE_SERVICE_ACCOUNT_JSON=$PWD/$SA_JSON" >> "$ENV_FILE"
else
  rm -f "$SA_JSON"
  MISSING+=("RITMO vault: '$GA_SA_ITEM_NAME' — 発行手順は doc/credential.md")
fi

CLARITY_TOKEN=$(op item get "$CLARITY_ITEM_ID" --vault "$RITMO_VAULT" \
    --fields password --reveal </dev/null 2>/dev/null || true)
if [ -n "$CLARITY_TOKEN" ]; then
  echo "CLARITY_API_TOKEN=$CLARITY_TOKEN" >> "$ENV_FILE"
else
  MISSING+=("RITMO vault: 'Microsoft Clarity APIキー' ($CLARITY_ITEM_ID)")
fi

echo "[setup] Done."
if [ ${#MISSING[@]} -gt 0 ]; then
  echo "[setup] 未取得の認証情報（揃ってから再実行すれば追記される）:" >&2
  printf '  - %s\n' "${MISSING[@]}" >&2
fi
echo "[setup] Test with: claude mcp list"
