#!/usr/bin/env bash
# setup.sh — 1Password から .mcp.json と .env を生成する（idempotent）
#
# 生成物:
#   .mcp.json  — mcp-wordpress 用（git 管理外）
#   .env       — wp-admin ログイン / GA4・GSC サービスアカウント / Clarity トークン（git 管理外）
#
# 1Password の配置:
#   vault `磯貝プライベート共有`:
#     - `programming-life.net MCP App Password`  … REST API 用 Application Password
#     - `programming-life.net`                   … wp-admin 通常ログイン
#   vault `RITMO`（解析系。発行手順は doc/credential.md）:
#     - `programming-life.net GA Service Account` … GA4 / Search Console 用 JSON キー
#     - `programming-life.net Clarity API Token`  … Clarity Data Export API トークン
set -euo pipefail

WP_VAULT_ID="vuhhrti25x7eq7g46mwtq7qome"        # 磯貝プライベート共有
APP_PW_ITEM_ID="e6oh5tuqlgcowbzqccmspttdcm"    # programming-life.net MCP App Password
LOGIN_ITEM_ID="v3hyideaoxwzyh57hkpfomzbhm"     # programming-life.net (wp-admin)
ANALYTICS_VAULT="RITMO"

MCP_JSON=".mcp.json"
ENV_FILE=".env"
SA_JSON="service-account-ga4.json"

if [ -f ~/ghq/getozinc/.envrc ]; then
  set -a; source ~/ghq/getozinc/.envrc 2>/dev/null; set +a
fi

command -v op >/dev/null || { echo "[ERROR] op (1Password CLI) not found." >&2; exit 1; }

echo "[setup] Fetching WordPress credentials from 1Password..."

APP_PW=$(op item get "$APP_PW_ITEM_ID" --vault "$WP_VAULT_ID" --fields password --reveal </dev/null 2>/dev/null || true)
[ -n "$APP_PW" ] || { echo "[ERROR] Application Password not found (item $APP_PW_ITEM_ID)." >&2; exit 1; }

WP_USER=$(op item get "$LOGIN_ITEM_ID" --vault "$WP_VAULT_ID" --fields username </dev/null 2>/dev/null || true)
WP_ADMIN_PW=$(op item get "$LOGIN_ITEM_ID" --vault "$WP_VAULT_ID" --fields password --reveal </dev/null 2>/dev/null || true)
[ -n "$WP_USER" ] || { echo "[ERROR] wp-admin username not found (item $LOGIN_ITEM_ID)." >&2; exit 1; }

echo "[setup] Writing $MCP_JSON ..."
cat > "$MCP_JSON" << MCPEOF
{
  "mcpServers": {
    "wordpress-programming-life": {
      "command": "npx",
      "args": ["-y", "mcp-wordpress"],
      "env": {
        "WORDPRESS_SITE_URL": "https://programming-life.net",
        "WORDPRESS_USERNAME": "$WP_USER",
        "WORDPRESS_APP_PASSWORD": "$APP_PW",
        "WORDPRESS_AUTH_METHOD": "app-password"
      }
    }
  }
}
MCPEOF

echo "[setup] Writing $ENV_FILE ..."
{
  echo "# Generated by setup.sh — do not commit"
  echo "WP_ADMIN_URL=https://programming-life.net/login_49954"
  echo "WP_ADMIN_USER=$WP_USER"
  echo "WP_ADMIN_PASSWORD=$WP_ADMIN_PW"
} > "$ENV_FILE"

MISSING=()

echo "[setup] Fetching analytics credentials (vault: $ANALYTICS_VAULT)..."
if op item get "programming-life.net GA Service Account" --vault "$ANALYTICS_VAULT" \
    --fields credential --reveal </dev/null > "$SA_JSON" 2>/dev/null && [ -s "$SA_JSON" ]; then
  echo "GOOGLE_SERVICE_ACCOUNT_JSON=$PWD/$SA_JSON" >> "$ENV_FILE"
else
  rm -f "$SA_JSON"
  MISSING+=("RITMO vault: 'programming-life.net GA Service Account' (doc/credential.md)")
fi

CLARITY_TOKEN=$(op item get "programming-life.net Clarity API Token" --vault "$ANALYTICS_VAULT" \
    --fields credential --reveal </dev/null 2>/dev/null || true)
if [ -n "$CLARITY_TOKEN" ]; then
  echo "CLARITY_API_TOKEN=$CLARITY_TOKEN" >> "$ENV_FILE"
else
  MISSING+=("RITMO vault: 'programming-life.net Clarity API Token' (doc/credential.md)")
fi

echo "[setup] Done."
if [ ${#MISSING[@]} -gt 0 ]; then
  echo "[setup] 未取得の認証情報（後で再実行すれば追記される）:" >&2
  printf '  - %s\n' "${MISSING[@]}" >&2
fi
echo "[setup] Test with: claude mcp list"
